{'application': False,
 'author': 'Nedas Zilinskas <nedas.zilinskas@gmail.com>',
 'auto_install': False,
 'category': 'Website',
 'contributors': 'Nedas Zilinskas <nedas.zilinskas@gmail.com>',
 'currency': 'EUR',
 'data': ['data/x_website_snippet.xml',
          'data/ir_actions_server.xml',
          'security/ir.model.access.csv',
          'views/assets.xml',
          'views/snippet.xml',
          'views/x_website_snippet.xml',
          'views/templates.xml'],
 'demo': [],
 'depends': ['website'],
 'description': 'Create your own custom Building Blocks',
 'external_dependencies': [],
 'images': ['static/description/main_screenshot.png'],
 'installable': True,
 'license': 'AGPL-3',
 'live_test_url': 'http://minilini.nedaszilinskas.com/page/create-custom-building-blocks',
 'maintainer': 'Nedas Zilinskas <nedas.zilinskas@gmail.com>',
 'name': 'Create Custom Building Blocks',
 'price': 40.0,
 'qweb': ['static/src/xml/*.xml'],
 'summary': 'Create your own custom Building Blocks',
 'support': 'nedas.zilinskas@gmail.com',
 'version': '9.0.1.0',
 'website': 'http://nedaszilinskas.com'}